# Generated by Django 5.1.2 on 2024-11-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='busted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
